[build]
builder = "DOCKERFILE"
dockerfilePath = "./docker/php/Dockerfile"

[deploy]
startCommand = "php artisan key:generate --force && php artisan storage:link && php artisan migrate --force --seed && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
