[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "docker-compose -f docker-compose.prod.yml up -d && docker-compose -f docker-compose.prod.yml exec -T php php artisan migrate --force"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
