[build]
builder = "DOCKERFILE"
dockerfilePath = "./docker/php/Dockerfile"

[deploy]
# startCommand removed to use Railway's default php-fpm/nginx handler
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
