[build]
builder = "DOCKERFILE"
dockerfilePath = "./docker/php/Dockerfile"

[deploy]
startCommand = "docker-compose -f docker-compose.prod.yml up -d"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
