[build]
builder = "DOCKERFILE"
dockerfilePath = "./docker/php/Dockerfile"

[deploy]
startCommand = "php artisan config:clear && php artisan route:clear && php artisan cache:clear && php artisan key:generate --force && php artisan storage:link && php artisan migrate --force --seed && (php artisan serve --host=0.0.0.0 --port=$PORT & sleep 5 && php artisan route:list && php artisan config:cache && php artisan route:cache && wait)"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
