[build]
builder = "DOCKERFILE"
dockerfilePath = "./docker/php/Dockerfile"

[deploy]
startCommand = "php artisan migrate --force --seed && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
