[build]
builder = "DOCKERFILE"
dockerfilePath = "./docker/php/Dockerfile"

[deploy]
startCommand = "chmod -R 777 storage bootstrap/cache && php artisan config:clear && php artisan cache:clear && php artisan route:clear && php artisan serve --host=0.0.0.0"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
